name: image_cache_uint8list
description: Download image from URL, cache it, and return Uint8List.
version: 0.0.1
homepage: https://github.com/thatbauaon-lo/image_cache_uint8list

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.0.0
  sqflite_common_ffi: ^2.3.0
